AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*
    - coverage/**/*
    - pkg/**/*

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - lib/registry.rb

Metrics/MethodLength:
  Max: 20

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/registry.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/registry.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/registry.rb

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - lib/registry.rb

Layout/LineLength:
  Max: 120
